# Site
name: "Driving Theory Test"
title: "Driving Theory Test"
description: "The driving theory test has two parts: a multiple-choice section and a hazard perception test. The multiple-choice section has 50 questions, and the hazard perception test has 75 clips. The pass mark for the multiple-choice section is 43 out of 50, and the pass mark for the hazard perception test is 44 out of 75. The test usually takes about 60 minutes to complete, but the length can vary depending on how quickly you answer"
logo: "assets/images/logo.png"
subheading: "Driving Theory Test"
cta-head: "Practice Tests"
cta-text: "Pass Your Driving Theory Test with Confidence"
cta-link: "/aff"
affiliate-link: "https://testbuddy.app/?ref=46"
logo: "assets/images/logo.png"
favicon: "assets/images/icon.png"
baseurl: ""
url:
google_analytics: ""
disqus: ""
mailchimp-list: ""
include: ["_pages"]
permalink: /:title/
email: press@bundldeals.xyz
formsfree: xwkalnqd

# Authors
authors:
  killcreek:
    name: killcreek
    display_name: killcreek
    avatar: "assets/images/avatar.png"
    email: mrgabonijeff@gmail.com
    gravatar: 298224aa0a009468d621d71b80cf8395
    web: https://www.webdevpl.us
    facebook: 
    description: "Web Developer/Designer🚀 turned SEO 🌐 / Writer 📝"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-admin
  - jekyll-compress-images

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 9
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-9114015255960073"
adsense-data-ad-slot: "5601250540"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
url: "https://drivingtheorytest.info"
shareurl: "https://drivingtheorytest.info"



 
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"

imageoptim:
  pngout: false
  svgo: false
  verbose: false

exclude:
  - _compress_images_cache.yml

