# Site
name: "Driving Theory Test"
title: "Driving Theory Test"
description: "Your journey to becoming a licensed driver starts here. Don't let the fear of failing your theory test stand in your way. Our proven strategies and effective study tools will empower you to succeed."
subheading: "Driving Theory Test"
cta-head: "Road and Traffic Sign Test"
cta-text: "Every day, we encounter and react to road signs. They play a crucial role in ensuring our safety while driving. But how well do you know your road signs?"
cta-link: "/test"
affiliate-link: "https://testbuddy.app/?ref=46"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.svg"
baseurl: ""
url:
google_analytics: ""
disqus: ""
mailchimp-list: ""
include: ["_pages"]
permalink: /:title/
email: press@bundldeals.xyz
formsfree: xwkalnqd

# Authors
authors:
  killcreek:
    name: killcreek
    display_name: killcreek
    avatar: "assets/images/avatar.png"
    email: mrgabonijeff@gmail.com
    gravatar: 298224aa0a009468d621d71b80cf8395
    web: https://www.webdevpl.us
    facebook: 
    description: "Web Developer/Designer🚀 turned SEO 🌐 / Writer 📝"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-admin
  - jekyll-compress-images

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 9
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-9114015255960073"
adsense-data-ad-slot: "5601250540"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
url: "https://drivingtheorytest.info"
shareurl: "https://drivingtheorytest.info"



 
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"

imageoptim:
  pngout: false
  svgo: false
  verbose: false

exclude:
  - _compress_images_cache.yml

